#!/bin/sh

## Tiling generator
rivertile -view-padding 5 -outer-padding 5 &
riverctl default-layout rivertile

## Input
riverctl input-config-type touchpad tap enabled

## Keybindings

# Open app menu
riverctl map normal Super D spawn fuzzel

# Open terminal
riverctl map normal Super Return spawn alacritty

# Close window
riverctl map normal Super Q close

# Exit
riverctl map normal Super+Shift E exit
